"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("../middleware/auth");
const aiController_1 = require("../controllers/aiController");
const geminiController_1 = require("../controllers/geminiController");
const router = (0, express_1.Router)();
router.use(auth_1.protect);
router.post('/chat', aiController_1.askAI);
router.post('/gemini/chat', geminiController_1.askGeminiAdvanced);
exports.default = router;
